### ISSUE TITLE
Adding multiple IP ranges on the sublocation

### ISSUE THREAD

**Issue by rameshmju1923** [willguibr/terraform-provider-zia#33]
Hi team, 
Comma separator is used when add multiple IP ranges in a sublocations. 
When we upload these data through CSV files, the comma separator will use by the csv file itself. So we cannot add more the one IP range for a sublocation.
We have to introduce another separator instead of comma (,) to add multiple IP ranges in a sublocation. 

Regards
Ramesh M

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- zpa_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by willguibr** [comment]
@rameshmju1923 The issue with empty field when creating a sub-location has been addressed in the PR#37.
