### ISSUE TITLE
Script to be abort a specific resource if the value is NULL.

### ISSUE THREAD

**Issue by rameshmju1923** [willguibr/terraform-provider-zia#35]
Hi team, 
I am planning to create  IP, GRE, location and sublocation through script from CSV files. If certain location doesn't have sub location, i will leave that ip range space. If any column without IP range has to trigger the script to abort. 

Regards
Ramesh M

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- zpa_xxx

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

**Comment by willguibr** [comment]
Closing this issue as it is duplicated as specified in the #33 and has been addressed in the PR #33
